name: Deploy Site on push
on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest codee
        uses: actions/checkout@v2.3.2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SITE_SERVER }}
          username: ${{ secrets.FTP_SITE_USERNAME }}
          password: ${{ secrets.FTP_SITE_PASSWORD }}